FROM amd64/ubuntu:18.04 as full
RUN apt-get update && apt-get install -y \
  git \
  && apt-get clean
ARG VERSION=master
ENV GRPC_RELEASE_TAG=$VERSION
RUN git clone -b ${GRPC_RELEASE_TAG} https://github.com/grpc/grpc /var/local/git/grpc \
  && cd /var/local/git/grpc \ 
  && git submodule update --init --recursive\
  && echo "grpc source downloaded to /var/local/git/grpc"


FROM scratch
COPY --from=full /var/local/git/grpc /var/local/git/grpc
