FROM amd64/ubuntu:18.04
RUN apt-get update && apt-get install -y \
  git \
  && apt-get clean
ENV GRPC_RELEASE_TAG v1.18.0
RUN git clone -b ${GRPC_RELEASE_TAG} https://github.com/grpc/grpc /var/local/git/grpc \
  && cd /var/local/git/grpc \ 
  && git submodule update --init --recursive\
  && echo "grpc source downloaded to /var/local/git/grpc"

  
